[project]
name = "benchmarking-nature-tsfm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.1",
    "xlrd>=2.0.2",
]
